name: TDL Annotation & Validation Pipeline (Generalized)

on:
  workflow_dispatch:
    inputs:
      folder:
        description: 'Name of the folder containing original TDL files'
        required: true
        default: 'src'

jobs:
  annotate-and-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install --upgrade pip

      - name: Run annotation script
        run: python scripts/tdl.py ${{ github.event.inputs.folder }} annotated_${{ github.event.inputs.folder }}

      - name: Create reports folder
        run: mkdir -p reports

      - name: Run comparison script
        run: python scripts/tdlcompare.py ${{ github.event.inputs.folder }} annotated_${{ github.event.inputs.folder }}

      - name: Upload annotated files
        uses: actions/upload-artifact@v4
        with:
          name: annotated-${{ github.event.inputs.folder }}
          path: annotated_${{ github.event.inputs.folder }}/

      - name: Upload comparison report
        uses: actions/upload-artifact@v4
        with:
          name: compare-report-${{ github.event.inputs.folder }}
          path: reports/compare_report_${{ github.event.inputs.folder }}.txt
